production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>

development:
  options:
    # raise_not_found_error: false
  clients:
    default:
      database: semana_academica
      hosts:
        - localhost:27017

test:
  clients:
      default:
        uri: mongodb+srv://arthursiqueiras:indeorum123@cluster0-rpte7.mongodb.net/test?retryWrites=true&w=majority
